name: Football Results - Stage 3

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-stage3:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Stage 3
        env:
          BIGBALLS_API_KEY: ${{ secrets.BIGBALLS_API_KEY }}
        run: |
          python main.py
