name: Test SportsAPI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت کد
        uses: actions/checkout@v4

      - name: نصب Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: نصب requests
        run: pip install requests

      - name: اجرای تست
        env:
          SPORTS_API_KEY: ${{ secrets.SPORTS_API_KEY }}
        run: python test_sportsapi.py
